#!/bin/sh
#
# nagioscore/ (../nagioscore, kuriyama/nagioscore の clone) の指定 ref から
# spec の Source0 が期待する形の tarball (nagioscore-nagios-<VERSION>.tar.gz)
# を再生成し、sources ファイルにハッシュを記録する。
#
# git archive はコミット日時をそのまま全エントリの mtime に使い、tree の
# エントリ順も常にソート済みなので、同じ ref から生成する限り tar の中身は
# 常にビットレベルで再現できる。gzip 層だけがバージョン依存でブレうるので、
# 「正」とするハッシュは圧縮前の tar の内容に対して取る。
#
# Usage: scripts/generate-source-tarball.sh [ref]
#   ref省略時は "al2023-<VERSION>" タグを使う。

set -e

VERSION=4.4.14
PREFIX="nagioscore-nagios-${VERSION}"
REF="${1:-al2023-${VERSION}}"

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_DIR=$(CDPATH= cd -- "${SCRIPT_DIR}/.." && pwd)
NAGIOSCORE_DIR="${REPO_DIR}/nagioscore"
OUT_TARGZ="${REPO_DIR}/${PREFIX}.tar.gz"
TMP_TAR=$(mktemp)
trap 'rm -f "${TMP_TAR}"' EXIT

if [ ! -d "${NAGIOSCORE_DIR}/.git" ]; then
	echo "error: ${NAGIOSCORE_DIR} is not a git checkout" >&2
	exit 1
fi

git -C "${NAGIOSCORE_DIR}" rev-parse --verify "${REF}" >/dev/null 2>&1 || {
	echo "error: ref '${REF}' not found in ${NAGIOSCORE_DIR}" >&2
	exit 1
}

git -C "${NAGIOSCORE_DIR}" archive --format=tar --prefix="${PREFIX}/" "${REF}" >"${TMP_TAR}"

TAR_SHA256=$(sha256sum "${TMP_TAR}" | awk '{print $1}')

gzip -n -9 -c "${TMP_TAR}" >"${OUT_TARGZ}"
TARGZ_SHA256=$(sha256sum "${OUT_TARGZ}" | awk '{print $1}')

RESOLVED_COMMIT=$(git -C "${NAGIOSCORE_DIR}" rev-parse "${REF}")

cat >"${REPO_DIR}/sources" <<EOF
# generated by scripts/generate-source-tarball.sh
# source: nagioscore @ ${REF} (${RESOLVED_COMMIT})
#
# authoritative: sha256 of the uncompressed tar content. Stable forever for
# a given ref, independent of gzip/zlib version used to compress it.
SHA256 (${PREFIX}.tar) = ${TAR_SHA256}
#
# informational only: sha256 of the actual .tar.gz produced on this machine
# (gzip -n -9). May differ across gzip/zlib versions even though the
# decompressed content (and the hash above) is identical.
SHA256 (${PREFIX}.tar.gz) = ${TARGZ_SHA256}
EOF

echo "wrote ${OUT_TARGZ}"
echo "updated ${REPO_DIR}/sources"
